# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 4
  ParameterListWrapping:
    indentSize: 4
build:
  maxIssues: 10 # break the build if ten weighted issues are found. TODO: fix
  weights:
    complexity: 2 # every rule of the complexity rule set should count as if two issues were found...
    LongParameterList: 1 # ...with the exception of the LongParameterList rule.